import 'server-only';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { cookies } from 'next/headers';
import { createAuthClient } from '@/lib/supabase/server';
import { checkCodeShape } from './admin-code';
import { ADMIN_CODE_COOLDOWN_SECONDS, checkAdminCodeLimit } from './email-limit';
import type { ID, User } from '@/lib/types';

/**
 * The second step an administrator takes before /admin opens.
 *
 * WHERE THE CODE COMES FROM. Supabase Auth, and nowhere else. FayTarra has no
 * mailer of its own — every message it has ever sent has been sent by Supabase
 * from its own templates — so a home-made code would have needed a second
 * email system to deliver it, which is exactly what this is not allowed to be.
 * `signInWithOtp` asks Supabase for a one-time code against an account that
 * already exists, and `verifyOtp` checks it.
 *
 * That choice does most of the security work by itself, because the code is
 * never FayTarra's to mishandle:
 *
 *   - generated by Supabase with a cryptographic RNG, server side;
 *   - stored by Supabase, hashed, never in a FayTarra table or log;
 *   - expiring on Supabase's own OTP lifetime;
 *   - single use — verifying it consumes it;
 *   - re-requesting replaces the stored token, so the previous code stops
 *     working the moment a new one is sent.
 *
 * Nothing here ever sees the code except the digits the admin types back
 * in, which are compared by Supabase rather than by this file.
 *
 * WHAT THIS FILE DOES OWN: the proof that the step was completed, as a short
 * signed cookie, and the rules about who may ask for a code at all.
 */

/** The flag that says this browser finished the second step. */
const COOKIE = 'fay_admin_verified';

/**
 * How long a completed verification lasts.
 *
 * Long enough to do a session's work without a code every few minutes, short
 * enough that a forgotten laptop is not an open admin console tomorrow.
 */
export const ADMIN_VERIFIED_SECONDS = 8 * 60 * 60;

/** How many wrong codes before the admin has to request a fresh one. */
export const MAX_CODE_ATTEMPTS = 5;



/**
 * The key the proof cookie is signed with.
 *
 * The service-role key is already the most privileged secret this server
 * holds, is present wherever the app can talk to its own database, and never
 * reaches a browser. Using it through HMAC does not expose it — a signature
 * does not reveal its key — and it means the admin step-up needs no new secret
 * to be provisioned before it works. `ADMIN_SESSION_SECRET` overrides it for
 * anyone who would rather keep the two apart.
 */
function signingKey(): string | null {
  return process.env.ADMIN_SESSION_SECRET || process.env.SUPABASE_SERVICE_ROLE_KEY || null;
}

function sign(payload: string, key: string): string {
  return createHmac('sha256', key).update(payload).digest('base64url');
}

/** Constant-time compare, so a signature cannot be guessed a byte at a time. */
function sameSignature(a: string, b: string): boolean {
  const left = Buffer.from(a);
  const right = Buffer.from(b);
  return left.length === right.length && timingSafeEqual(left, right);
}

/**
 * Failed attempts and code requests, per account, in memory.
 *
 * Per instance and therefore best effort, exactly like the upload and email
 * limiters this sits beside. It is not the only thing standing between an
 * attacker and the code: Supabase expires the token, invalidates it on the
 * next send, and applies its own send rate limit. This makes a brute force
 * expensive rather than merely slow, and it is why a run of wrong codes burns
 * the code rather than just pausing.
 */
const attempts = new Map<ID, number>();

export type StepUpResult = { ok: true; cooldownSeconds: number } | { ok: false; error: string };

/**
 * Asks Supabase to email a fresh code to the ADMIN'S OWN address.
 *
 * The address is read from the signed-in profile, never from the request, so
 * there is nothing here to point at somebody else's inbox. Only an active
 * admin gets this far — a normal account cannot reach the caller.
 */
export async function sendAdminCode(admin: User): Promise<StepUpResult> {
  if (admin.role !== 'admin') return { ok: false, error: 'That account is not an administrator.' };
  if (admin.status !== 'active') return { ok: false, error: 'That account is not active.' };

  const gate = checkAdminCodeLimit(admin.email);
  if (!gate.ok) return { ok: false, error: gate.error };

  const supabase = await createAuthClient();
  if (!supabase) return { ok: false, error: 'Sign-in is not configured.' };

  const { error } = await supabase.auth.signInWithOtp({
    email: admin.email,
    options: {
      // This must never be able to CREATE anything. It is a second factor for
      // an account that already exists, not a way in.
      shouldCreateUser: false,
    },
  });

  if (error) {
    const message = (error.message ?? '').toLowerCase();
    if (error.status === 429 || message.includes('rate limit') || message.includes('security purposes')) {
      return { ok: false, error: 'Too many codes requested. Wait a moment and try again.' };
    }
    return { ok: false, error: 'Could not send the code. Try again in a moment.' };
  }

  // A new code has been issued, so the old one is dead at Supabase and the
  // attempt budget starts again.
  attempts.delete(admin.id);
  return { ok: true, cooldownSeconds: ADMIN_CODE_COOLDOWN_SECONDS };
}

export type VerifyResult = { ok: true } | { ok: false; error: string; exhausted?: boolean };

/**
 * Checks the digits against Supabase and, if they are right, records that
 * this browser has completed the step.
 *
 * The code is handed straight to Supabase. It is never compared here, never
 * written down, and never logged.
 */
export async function verifyAdminCode(admin: User, code: string): Promise<VerifyResult> {
  if (admin.role !== 'admin') return { ok: false, error: 'That account is not an administrator.' };

  // Checked BEFORE the attempt budget is touched. A code of the wrong length
  // was never a guess at the right one, so it must not cost an attempt — which
  // matters most when the project's OTP length has drifted and every code in
  // the inbox is the wrong size.
  const shape = checkCodeShape(code);
  if (!shape.ok) return { ok: false, error: shape.error };
  const digits = shape.digits;

  const used = attempts.get(admin.id) ?? 0;
  if (used >= MAX_CODE_ATTEMPTS) {
    return {
      ok: false,
      exhausted: true,
      error: 'Too many incorrect codes. Send yourself a new one.',
    };
  }

  const supabase = await createAuthClient();
  if (!supabase) return { ok: false, error: 'Sign-in is not configured.' };

  /**
   * `signInWithOtp` issues what GoTrue calls a magic-link token, and the same
   * digits are what `{{ .Token }}` renders. Which name `verifyOtp` wants
   * for it — 'email' or 'magiclink' — has moved between GoTrue versions, and
   * the wrong name simply misses the lookup: the token is NOT consumed by a
   * failed verify, so trying the other name costs nothing and removes a
   * version dependency that would otherwise look exactly like a wrong code.
   *
   * Only this one pair is ever tried. No other type is substituted.
   */
  let result = await supabase.auth.verifyOtp({
    email: admin.email,
    token: digits,
    type: 'email',
  });

  if (result.error && !result.data.user) {
    result = await supabase.auth.verifyOtp({
      email: admin.email,
      token: digits,
      type: 'magiclink',
    });
  }

  const { data, error } = result;

  if (error || !data.user) {
    const left = MAX_CODE_ATTEMPTS - (used + 1);
    attempts.set(admin.id, used + 1);
    if (left <= 0) {
      return { ok: false, exhausted: true, error: 'Too many incorrect codes. Send yourself a new one.' };
    }
    return {
      ok: false,
      error: `That code is not right. ${left} attempt${left === 1 ? '' : 's'} left.`,
    };
  }

  // Verifying consumed the code at Supabase; a replay of the same digits now
  // fails there, not here.
  attempts.delete(admin.id);
  await grantAdminVerification(admin.id);
  return { ok: true };
}

/** Writes the proof cookie. Nothing readable, nothing reusable elsewhere. */
async function grantAdminVerification(userId: ID): Promise<void> {
  const key = signingKey();
  if (!key) return;

  const expires = Math.floor(Date.now() / 1000) + ADMIN_VERIFIED_SECONDS;
  // Bound to the account, so a cookie cannot be carried to another session.
  const payload = `${userId}.${expires}`;
  const store = await cookies();
  store.set(COOKIE, `${payload}.${sign(payload, key)}`, {
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
    path: '/',
    maxAge: ADMIN_VERIFIED_SECONDS,
  });
}

/** Drops the proof, so the next visit to /admin asks again. */
export async function clearAdminVerification(): Promise<void> {
  const store = await cookies();
  store.delete(COOKIE);
}

/**
 * Has THIS browser completed the step for THIS account?
 *
 * Fails closed. An unreadable cookie, a signature that does not check out, an
 * expiry in the past, a different account, or no signing key at all all mean
 * no — /admin stays shut and the admin is asked for a code.
 */
export async function hasAdminVerification(userId: ID): Promise<boolean> {
  const key = signingKey();
  if (!key) return false;

  const raw = (await cookies()).get(COOKIE)?.value;
  if (!raw) return false;

  const parts = raw.split('.');
  if (parts.length !== 3) return false;
  const [sub, expires, signature] = parts;

  if (sub !== userId) return false;

  const expiresAt = Number(expires);
  if (!Number.isFinite(expiresAt) || expiresAt * 1000 <= Date.now()) return false;

  return sameSignature(signature, sign(`${sub}.${expires}`, key));
}
